server:
  port: 9001

logging:
  level:
    org.springframework.security: trace


#
#spring:
#  security:
#    oauth2:
#      client:
#        use-current-uri:false

#spring:
#  security:
#    oauth2:
#      authorizationserver:
#        client:
#          oidc-client:
#            registration:
#              client-id: "client"
#              client-secret: "123456"
#              client-authentication-methods:
#                - "client_secret_basic"
#              authorization-grant-types:
#                - "authorization_code"
#                - "refresh_token"
#              redirect-uris:
#                - "http://localhost:9001/oauth2/authorize"
#              post-logout-redirect-uris:
#                - "http://localhost:9001/"
#              scopes:
#                - "openid"
#                - "profile"
#            require-authorization-consent: true